name: test
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
       
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  

    - name: Determine changed files
      id: changed_files
      run: |
        git diff --name-only HEAD^ HEAD | grep '\.php$'
        
    - uses: php-actions/phpstan@v3
      with:
        php_version: 8.1
        path: ${{ steps.changed_files.outputs.files }}        
